config/routes.rb
Rails.application.routes.draw do
  root    'top#index'
  post    'post'         =>  'top#create'
  get     'new'          =>  'top#new'
  post    'new/post'     =>  'top#new_tag'
  post    'tag'          =>  'top#tag'
  get     'tag_delete'   =>  'top#tag_delete'
  post    'users_name'   =>  'top#users_name'
  get 	  'all' 		=>	'top#all'
  post 	  'all_post' 		=>	'top#all_post'
  delete  'all_delete'     => 'top#all_delete'


  get     'takahiro'   =>    'top#takahiro'
  post    'takahiro/post'    =>  'top#takahiro_create'
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/middle.rb
class Middle < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/takahiro.rb
class Takahiro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController

	def all
		@pages = Page.all
		@new_page = Page.new
	end

	def all_post
		@new_page = Page.new
		@new_page.page_name = params[:page][:page_name]
		@new_page.takahiro_flag = params[:page][:takahiro_flag]
		@new_page.save
		redirect_to :all
	end

	def all_delete
		deletePage = Page.find_by_id(params[:id])
		deletePage.destroy
		redirect_to :all
	end

	def index
		if session[:user_name] == nil
			flash.notice = '名前を入力してください。'
		end
		@new_comment = Comment.new
		@new_middle = Middle.new
		unless @page = Page.find_by(id: params[:page])
			redirect_to :action => :all
		end

		@comments = Comment.where(page: params[:page])
		@tags = Tag.where(page: params[:page])
	end

	def create
		@new_comment = Comment.new
		@new_comment.user_name = session[:user_name]
		@new_comment.comment = params[:comment][:comment]
		@new_comment.page = params[:page]
		if @new_comment.save
			redirect_to :back 
		else
			redirect_to :back
		end
	end

	def new
		@tag = Tag.new
		@all_tag = Tag.where(page: params[:page])
		@page = Page.find_by_id(params[:page])
		@back_url = params[:page]
	end

	def new_tag
		@tag = Tag.new
		@tag.tag_name = params[:tag][:tag_name]
		@tag.page = params[:page]
		if @tag.save
			redirect_to :back
		else
			redirect_to :back
		end
	end

	def tag
		@middle = Middle.new
		@middle.tag_id = params[:middle][:tag_id]
		@middle.comment_id = params[:middle][:comment_id]

		added_comments = Middle.where(comment_id: params[:middle][:comment_id])
		unless added_comments.count == 0
			added_comments.each do |comment|
				unless comment.tag_id.round == params[:middle][:tag_id].to_i.round
					@middle.save
				end
			end
		else
			@middle.save
		end

		redirect_to :back
		
	end
	def tag_delete
		@del_middle = Middle.where(comment_id:params[:comment], tag_id: params[:tag])
		@del_middle[0].destroy
		redirect_to :back
	end

	def users_name
		session[:user_name] = params[:name]
		redirect_to :back
	end

	def takahiro
		if session[:user_name] == nil
			flash.notice = '名前を入力してください。'
		end
		@page = Page.find_by_id(params[:page])
		@new_comment = Takahiro.new
		@comments = Takahiro.where(page: params[:page])
	end
	def takahiro_create
		@new_comment = Takahiro.new
		@new_comment.user_name = session[:user_name]
		@new_comment.comment = params[:takahiro][:comment]
		@new_comment.page = params[:page]
		if @new_comment.save
			redirect_to :back
		else
			redirect_to :back
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImportantComment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/all.html.erb
	<div class="main">
		<!-- がんばれー笑 -->
		<div class="header">
			<div class="wrap">
				<h1><a href="/all">Hoshino Takahiroの卒論</a></h1>
			</div>
		</div>
		<div class="main">
			<div class="wrap">
				<div class="left_main">
					<% @pages.each do |page| %>

						<div class="comment">
							<% if page.takahiro_flag == true %>
								<a href="/takahiro/?page=<%= page.id %>"><h3><%= page.page_name %></h3></a>
							<% else %>
								<a href="/?page=<%= page.id %>"><h3><%= page.page_name %></h3></a>
							<% end %>
								<%= link_to 'delete', all_delete_path(:id => page.id), :method => :delete if session[:user_name] == "saaan"  %>
						</div>

					<% end %>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="wrap">
				<%= form_for(@new_page, url: :all_post) do |f| %>
					<%= f.label :page_name, '新規スレッド作成', :class => 'mt-10' %>
                    <%= f.text_field :page_name %>
                    <%= f.label :takahiro_flag, 'タグ無し verにする', :class => 'mt-10' %>
                    <%= f.check_box :takahiro_flag , {}, true, false %>
                    <%= f.submit '作成！' %>
				<% end %>
			</div>
		</div>
		</div>
	</div>

app/views/top/index.html.erb
<% if flash.notice || flash.alert %>
    <div class="notice_block">
        <div class="wrap">
            <%= content_tag(:span, flash.notice, class: 'notice')  %>
            <%= form_tag('/users_name') do %>
            	<input type="text" name="name">
            	<%= submit_tag() %>
            <% end %>
        </div>
    </div>
<% end %>
	<div class="main">
		<!-- がんばれー笑 -->
		<div class="header">
			<div class="wrap">
				<h1><a href="/all"><%= @page.page_name ||= "Hoshino Takahiroの卒論" %>　<span>（一覧に戻る）</span></a></h1>
				<p><a href="/new?page=<%= params[:page] %>" class="new_tag">NEW TAG</a></p>
			</div>
		</div>
		<div class="main">
			<div class="wrap">
				<div class="left_main">
					<% @comments.each do |comment| %>

						<div id="<%= comment.id %>" class="comment <%= "own_comment" if comment.user_name == session[:user_name]  %>">
							<p><span class="user"><%= comment.user_name %></span><span class="settime"><%= comment.created_at.strftime('%H:%M:%S') %></span></p>
							<h3><%= comment.comment %></h3>
							<%= form_for(@new_middle, url: :tag) do |f| %>
							  <%= f.label :tag_id %>
							  <%= f.collection_select :tag_id, Tag.where(page: params[:page]), :id, :tag_name, {} ,{:class => "form-control"} %>
							  <input type="hidden" name="middle[comment_id]" id="middle_comment_id" value="<%= comment.id %>" />
							  <input type="hidden" name="page" id="page" value="<%= params[:page] %>" />
							  <%= f.submit 'タグセット' , :class => 'tag_set'%>
							  
							<% end %>
						</div>

					<% end %>
					<div class="footer">
							<%= form_for(@new_comment, url: :post, authenticity_token: true) do |f| %>
								<%= f.label :comment, 'コメント投稿', :class => 'mt-10' %>
			                    <%= f.text_area :comment %>
			                    <input type="hidden" name="page" id="page" value="<%= params[:page] %>" />
			                    <%= f.submit '投稿' %>
							<% end %>
					</div>
				</div>
				<div class="right_main">
					<div class="scroll">
						<% @tags.each do |tag| %>
							<div class="tag">
								<h3><%= tag.tag_name %></h3>
								<% @middles = Middle.where(tag_id: tag.id) %>
								<ul>
									<% @middles.each do |middle| %>
										<% @comments = Comment.where(id: middle.comment_id) %>
											<% @comments.each do |comment| %>
											<li class="set_tag"><%= comment.comment %>
											<a href="/tag_delete?comment=<%= comment.id %>&tag=<%= tag.id %>">削除</a></li>
										<% end %>
									<% end %>
								</ul>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		
		</div>
	</div>

app/views/top/new.html.erb
<% if flash.notice || flash.alert %>
    <div class="notice_block">
        <div class="wrap">
            <%= content_tag(:span, flash.notice, class: 'notice')  %>
            <%= form_tag('/users_name') do %>
            	<input type="text" name="name">
            	<%= submit_tag() %>
            <% end %>
        </div>
    </div>
<% end %>
	<div class="main">
		<!-- がんばれー笑 -->
		<div class="header">
			<div class="wrap">
				<h1><a href="/all">『<%= @page.page_name ||= "Hoshino Takahiroの卒論" %>』のタグ追加</a></h1>
				<p><a href="/?page=<%= @back_url %>">戻る</a></p>
			</div>
		</div>
		<div class="footer">
			<div class="wrap">
				<h3>タグ一覧</h3>
				<% @all_tag.each do |tag_tag| %>
				<p><%= tag_tag.tag_name %></p>
				<% end %>
				<%= form_for(@tag, url: :new_post) do |f| %>
					<%= f.label :tag_name, '新しいタグ', :class => 'mt-10' %>
                    <%= f.text_area :tag_name %>
                    <input type="hidden" name="page" id="page" value="<%= params[:page] %>" />
                    <%= f.submit '投稿' %>
				<% end %>
			</div>
		</div>
		</div>
	</div>

app/views/top/takahiro.html.erb
<% if flash.notice || flash.alert %>
    <div class="notice_block">
        <div class="wrap">
            <%= content_tag(:span, flash.notice, class: 'notice')  %>
            <%= form_tag('/users_name') do %>
            	<input type="text" name="name">
            	<%= submit_tag() %>
            <% end %>
        </div>
    </div>
<% end %>
	<div class="main">
		<!-- がんばれー笑 -->
		<div class="header">
			<div class="wrap">
				<h1><a href="/all"><%= @page.page_name ||= "Hoshino Takahiroの卒論" %>　<span>（一覧に戻る）</span></a></h1>
			</div>
		</div>
		<div class="main">
			<div class="wrap">
				<div class="left_main">
					<% @comments.each do |comment| %>

						<div id="<%= comment.id %>" class="comment <%= "own_comment" if comment.user_name == session[:user_name]  %>">
							<p><span class="user"><%= comment.user_name %></span><span class="settime"><%= comment.created_at.strftime('%H:%M:%S') %></span></p>
							<h3><%= comment.comment %></h3>
						
						</div>

					<% end %>
				</div>
			</div>
		</div>
		<div class="footer">
			<div class="wrap">
				<%= form_for(@new_comment, url: :takahiro_post) do |f| %>
					<%= f.label :comment, 'コメント投稿', :class => 'mt-10' %>
					<input type="hidden" name="page" id="page" value="<%= params[:page] %>" />
                    <%= f.text_area :comment %>
                    <%= f.submit '投稿' %>
				<% end %>
			</div>
		</div>
		</div>
	</div>